name: Update Security RSS Feed with Groq

on:
  schedule:
    - cron: '5,15,25,35,45,55 * * * *'  # Co 10 minut, z przesunięciem o 5 min
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-security-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Fetch Security RSS and enhance with Groq
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: |
        cat > fetch-security-groq.js << 'EOF'
        const https = require('https');
        const fs = require('fs');
        
        const RSS_URL = 'https://defence24.pl/_rssd';
        const GROQ_API_KEY = process.env.GROQ_API_KEY;
        
        // Funkcja do sprawdzania podobieństwa tekstów
        function calculateSimilarity(text1, text2) {
          const words1 = text1.toLowerCase().split(/\s+/);
          const words2 = text2.toLowerCase().split(/\s+/);
          
          const set1 = new Set(words1);
          const set2 = new Set(words2);
          
          const intersection = new Set([...set1].filter(x => set2.has(x)));
          const union = new Set([...set1, ...set2]);
          
          return intersection.size / union.size;
        }
        
        // Funkcja do przekształcania tytułu przez Groq
        async function enhanceTitleWithGroq(originalTitle) {
          const prompt = "ZADANIE: Przepisz tytuł artykułu o bezpieczeństwie i obronności na bardziej neutralny i faktyczny.\n\n" +
            "WYMAGANIA:\n" +
            "- Usuń clickbaitowe elementy\n" +
            "- Zachowaj wszystkie fakty militarne i polityczne\n" +
            "- Napisz w stylu informacyjnym, nie sensacyjnym\n" +
            "- Bez cudzysłowów i wykrzykników\n" +
            "- Maksymalnie 80 znaków\n" +
            "- Precyzyjny i merytoryczny ton\n" +
            "- Zachowaj nazwy krajów, organizacji i sprzętu wojskowego\n\n" +
            "ORYGINALNY TYTUŁ:\n" +
            originalTitle + "\n\n" +
            "PRZEPISANY TYTUŁ:";
        
          const requestData = JSON.stringify({
            messages: [
              {
                role: "system",
                content: "Jesteś ekspertem od spraw obronności specjalizującym się w pisaniu neutralnych, informacyjnych tytułów bez clickbaitu."
              },
              {
                role: "user",
                content: prompt
              }
            ],
            model: "llama-3.3-70b-versatile",
            temperature: 0.3,
            max_tokens: 100,
            top_p: 0.9
          });
        
          return new Promise((resolve, reject) => {
            const options = {
              hostname: 'api.groq.com',
              path: '/openai/v1/chat/completions',
              method: 'POST',
              headers: {
                'Authorization': 'Bearer ' + GROQ_API_KEY,
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(requestData)
              },
              timeout: 15000
            };
        
            const req = https.request(options, (res) => {
              let data = '';
              res.on('data', chunk => data += chunk);
              res.on('end', () => {
                try {
                  if (res.statusCode !== 200) {
                    console.log('Groq API error for title:', res.statusCode);
                    resolve(originalTitle);
                    return;
                  }
                  
                  const response = JSON.parse(data);
                  let enhancedTitle = response.choices[0].message.content.trim();
                  enhancedTitle = enhancedTitle.replace(/^["']|["']$/g, '');
                  
                  console.log('Enhanced title:', enhancedTitle);
                  resolve(enhancedTitle);
                  
                } catch (error) {
                  console.log('Title enhancement error:', error);
                  resolve(originalTitle);
                }
              });
            });
        
            req.on('error', () => resolve(originalTitle));
            req.on('timeout', () => {
              req.destroy();
              resolve(originalTitle);
            });
        
            req.setTimeout(15000);
            req.write(requestData);
            req.end();
          });
        }
        
        // Funkcja do ulepszania opisu przez Groq
        async function enhanceDescriptionWithGroq(title, originalDescription) {
          const prompt = "ZADANIE: Przekształć ten opis artykułu o bezpieczeństwie w listę punktową wszystkich informacji.\n\n" +
            "WYMAGANIA:\n" +
            "- Wypunktuj WSZYSTKIE informacje z opisu\n" +
            "- Każdy punkt w nowej linii z • na początku\n" +
            "- Zachowaj wszystkie szczegóły (liczby, miejsca, osoby, sprzęt wojskowy)\n" +
            "- Nie skracaj ani nie pomijaj żadnych danych\n" +
            "- NIE DUPLIKUJ informacji z tytułu w punktach\n" +
            "- Nie dodawaj własnych komentarzy\n" +
            "- Tylko faktyczne informacje z tekstu opisu\n" +
            "- Zachowaj nazwy krajów, sojuszy, jednostek wojskowych\n\n" +
            "Opis artykułu: " + originalDescription + "\n\n" +
            "LISTA PUNKTOWA:";
        
          const requestData = JSON.stringify({
            messages: [
              {
                role: "system",
                content: "Jesteś ekspertem od strukturyzowania informacji militarnych i obronnych. Zawsze przekształcasz tekst w przejrzystą listę punktową zachowując wszystkie szczegóły."
              },
              {
                role: "user",
                content: prompt
              }
            ],
            model: "llama-3.3-70b-versatile",
            temperature: 0.2,
            max_tokens: 500,
            top_p: 0.9
          });
        
          return new Promise((resolve, reject) => {
            const options = {
              hostname: 'api.groq.com',
              path: '/openai/v1/chat/completions',
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${GROQ_API_KEY}`,
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(requestData)
              },
              timeout: 15000
            };
        
            const req = https.request(options, (res) => {
              let data = '';
              res.on('data', chunk => data += chunk);
              res.on('end', () => {
                try {
                  if (res.statusCode !== 200) {
                    console.log(`Groq API error ${res.statusCode}:`, data);
                    resolve(originalDescription);
                    return;
                  }
                  
                  const response = JSON.parse(data);
                  let enhancedText = response.choices[0].message.content.trim();
                  
                  enhancedText = enhancedText.replace(/^["']|["']$/g, '');
                  
                  const similarity = calculateSimilarity(originalDescription, enhancedText);
                  if (similarity > 0.8) {
                    console.log(`Tekst zbyt podobny (${Math.round(similarity * 100)}%), pozostawiam oryginalny...`);
                    resolve(originalDescription);
                  } else {
                    console.log(`Enhanced (${Math.round(similarity * 100)}% podobieństwo): ${enhancedText.substring(0, 50)}...`);
                    resolve(enhancedText);
                  }
                } catch (error) {
                  console.log('JSON parse error:', error);
                  resolve(originalDescription);
                }
              });
            });
        
            req.on('error', (error) => {
              console.log('Groq request error:', error);
              resolve(originalDescription);
            });
        
            req.on('timeout', () => {
              console.log('Groq request timeout');
              req.destroy();
              resolve(originalDescription);
            });
        
            req.setTimeout(15000);
            req.write(requestData);
            req.end();
          });
        }
        
        function delay(ms) {
          return new Promise(resolve => setTimeout(resolve, ms));
        }
        
        function fetchRSS() {
          return new Promise((resolve, reject) => {
            const options = {
              hostname: 'defence24.pl',
              path: '/_rssd',
              method: 'GET',
              headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'Accept': 'application/rss+xml, application/xml, text/xml',
                'Accept-Language': 'pl-PL,pl;q=0.9,en;q=0.8',
                'Cache-Control': 'no-cache'
              },
              timeout: 10000
            };
            
            const req = https.request(options, (res) => {
              if (res.statusCode === 301 || res.statusCode === 302) {
                const location = res.headers.location;
                if (location) {
                  const url = new URL(location);
                  const newOptions = {
                    hostname: url.hostname,
                    path: url.pathname + url.search,
                    method: 'GET',
                    headers: options.headers,
                    timeout: 10000
                  };
                  
                  const redirectReq = https.request(newOptions, (redirectRes) => {
                    if (redirectRes.statusCode !== 200) {
                      reject(new Error(`HTTP ${redirectRes.statusCode}`));
                      return;
                    }
                    
                    let data = '';
                    redirectRes.on('data', chunk => data += chunk);
                    redirectRes.on('end', () => resolve(data));
                  });
                  
                  redirectReq.on('error', reject);
                  redirectReq.setTimeout(10000);
                  redirectReq.end();
                  return;
                }
              }
              
              if (res.statusCode !== 200) {
                reject(new Error(`HTTP ${res.statusCode}`));
                return;
              }
              
              let data = '';
              res.on('data', chunk => data += chunk);
              res.on('end', () => resolve(data));
            });
            
            req.on('error', reject);
            req.on('timeout', () => {
              req.destroy();
              reject(new Error('Request timeout'));
            });
            
            req.setTimeout(10000);
            req.end();
          });
        }
        
        function parseRSS(xml) {
          const items = [];
          const itemParts = xml.split('<item>');
          
          for (let i = 1; i < itemParts.length; i++) {
            const item = itemParts[i].split('</item>')[0];
            
            let title = '';
            let link = '';
            let pubDate = '';
            let description = '';
            
            const titleMatch = item.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/) || 
                              item.match(/<title>(.*?)<\/title>/);
            if (titleMatch) title = titleMatch[1];
            
            const linkMatch = item.match(/<link>(.*?)<\/link>/);
            if (linkMatch) link = linkMatch[1];
            
            const dateMatch = item.match(/<pubDate>(.*?)<\/pubDate>/);
            if (dateMatch) pubDate = dateMatch[1];
            
            const descMatch = item.match(/<description>\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*<\/description>/) ||
                             item.match(/<description>([\s\S]*?)<\/description>/);
            if (descMatch) {
              let rawDesc = descMatch[1];
              description = rawDesc.replace(/<[^>]*>/g, '').trim();
              description = description.replace(/\s+/g, ' ').trim();
            }
            
            if (title && link) {
              items.push({
                title: title.trim(),
                link: link.trim(),
                pubDate: pubDate.trim(),
                description: description || 'Brak opisu'
              });
            }
            
            if (items.length >= 10) break;
          }
          
          return items;
        }
        
        async function main() {
          try {
            if (!GROQ_API_KEY) {
              console.log('BŁĄD: GROQ_API_KEY nie jest ustawiony!');
              throw new Error('GROQ_API_KEY nie jest ustawiony');
            }
            
            console.log('Pobieranie RSS Defence24...');
            const xml = await fetchRSS();
            const articles = parseRSS(xml);
            
            console.log(`Pobrano ${articles.length} artykułów, ulepszanie opisów...`);
            
            for (let i = 0; i < articles.length; i++) {
              const article = articles[i];
              
              if (article.description && article.description !== 'Brak opisu') {
                console.log(`\\n=== PRZETWARZANIE ${i + 1}/${articles.length} ===`);
                console.log(`Oryginalny tytuł: ${article.title}`);
                console.log(`Oryginalny opis: ${article.description.substring(0, 100)}...`);
                
                const enhancedTitle = await enhanceTitleWithGroq(article.title);
                console.log(`Nowy tytuł: ${enhancedTitle}`);
                
                await delay(1500);
                
                const enhancedDescription = await enhanceDescriptionWithGroq(
                  article.title,
                  article.description
                );
                
                console.log(`Nowy opis: ${enhancedDescription.substring(0, 100)}...`);
                
                articles[i].originalTitle = article.title;
                articles[i].originalDescription = article.description;
                articles[i].title = enhancedTitle;
                articles[i].description = enhancedDescription;
                
                if (i < articles.length - 1) {
                  console.log('Czekam 2 sekundy...');
                  await delay(2000);
                }
              } else {
                console.log(`Pomijam artykuł ${i + 1} - brak opisu`);
              }
            }
            
            const data = {
              lastUpdate: new Date().toISOString(),
              enhancedWithGroq: true,
              groqApiKeyExists: !!GROQ_API_KEY,
              source: 'Defence24.pl',
              articles: articles
            };
            
            fs.writeFileSync('security.json', JSON.stringify(data, null, 2));
            console.log(`\\nZAPISANO ${articles.length} artykułów o bezpieczeństwie`);
            
          } catch (error) {
            console.error('BŁĄD W MAIN:', error);
            
            const fallbackData = {
              lastUpdate: new Date().toISOString(),
              enhancedWithGroq: false,
              error: error.message,
              source: 'Defence24.pl',
              articles: []
            };
            
            fs.
